### PR TITLE
Cm 13.0

### PR DESCRIPTION
**Pull request by MrMike21822**
Hey bro I wanna pull this.

### CODE REVIEW

**Comment by r3pwn** [comment]
I wouldn't recommend pulling this yet. I have yet to even get cm13 to get to the boot animation.

**Comment by r3pwn** [comment]
I see that, despite my warning, you merged this anyways. In its current state, it won't even get to the boot animation until you pull in the required kernel and vendor changes. With those previously mentioned changes, it gets to the boot animation, but no further.

**Comment by rbheromax** [comment]
i cloned my original branch before the merge*, will do some branch renaming in a sec. i'll pull all those down and try some test builds while im out today

**Comment by rbheromax** [comment]
any way around jack and jill compilers freezing my build process?

**Comment by r3pwn** [comment]
I don't have that issue. What specs does your build PC have?

**Comment by rbheromax** [comment]
i5 3230QM - 3.2 GHz Dual-Core/HT
12 GB DDR3 1600 MHz
768 GB Seagate 7200 RPM HDD
Nvidia GeForce GTX 660M

Running inside a VM with 2 threads dedicated and 6 GB RAM
Moto G (cm_titan) builds compile in ~2-3 hours from "make clobber"
I hang on compiling 5-6th? apk process after issuing "mka bacon". If I interrupt and start again it'll freeze around 5-6 targets later. This is with the Jack and Jill compilers from Google

**Comment by r3pwn** [comment]
Hmm... I have no idea how to help you there. My PC's (actually a laptop) specs are Intel Core i3 with 4 gigs of ram, so you should have more than enough.

**Comment by rbheromax** [comment]
I'll just do a native install on another computer. Try it from there. I'll probably get better results. Has any progress been made yet on the rom?

**Comment by r3pwn** [comment]
Well, I have it booting to the boot animation. I needed to update the adreno blobs and implement the new selinux kernel stuff to get that far, now just time to debug why it won't go any further.

**Comment by rbheromax** [comment]
Changed my VM specs:
Single Thread (Core)
6 GB RAM
Increased HDD, Decreased Swap to ~1.5GB

Completed and flashed CM13.0 userdebug and is stuck on boot animation like you said, about to build eng now to grab some logs

**Comment by r3pwn** [comment]
Okay. I briefly looked through the logs, but saw nothing of any importance, and was kinda confused. Maybe more kernel changes are needed...

**Comment by rbheromax** [comment]
Kernel seems to be fine, either something is being denied access to write, or cache isn't being mounted at all. I'll cross-reference the ramdisk with whatever logs I can come up with to try and track down some problems. Any chance you could advance me some logs through pastebin?

**Comment by rbheromax** [comment]
sound_trigger.msm8226.so / sound_trigger.default.so is missing?
either track it down, re-do the entire audio HAL to keep camera from crashing, or remove camera HAL to not make it crash anymore.
thats ONE problem, netd doesnt seem to launch at all. I can get to netd launching if I remove camera HAL but then it gets denied execution it seems. SELinux stuff maybe?

**Comment by r3pwn** [comment]
I thought I did remove the camera stuff because it was keeping cm12.1 from booting. Oh well. I'll look at it maybe within the next week.

**Comment by rbheromax** [comment]
also in <device tree>/init/init_a11.c

remove everything defining a devce (ie product, device name, and kitkat build fingerprint)
that'll cause issues with zygote and build.prop

**Comment by r3pwn** [comment]
How would it cause those issues? It works for other devices (ones with official support, too). Feel free to remove it from your device tree, though.

**Pull request merged**
